name: Swift CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files (Debug)
        run: ls -la

      - name: Compile Swift File
        run: swiftc main.swift -o myApp

      - name: Run Compiled App
        run: ./myApp
