name: Swift CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: swift:6.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Project Structure (Debugging)
        run: ls -R

      - name: Navigate to Correct Directory
        run: cd GitHubCLI && ls -la
      
      - name: Build Swift Package
        run: cd GitHubCLI && swift build --configuration release

      - name: Run Tests
        run: cd GitHubCLI && swift test
